# Generated by Django 5.0.1 on 2024-01-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name_plural': 'Dictionaries'},
        ),
    ]
